### Predicción del desempeño: MSLQ + Lab1

1. Predicir el desempeño del estudiante con el algoritmo Árbol de Decisión (Clasificación)
2. Predecir la calificación del lab_1 con el algoritmo Árbol de Decisión (Regresión)

El umbral de desempeño es:

- 0 - Bajo desempeño  (calificación entre 0.0 y 2.9)
- 1 - Medio desempeño (calificación entre 3.0 y 4.0)
- 2 - Alto desempeño  (calificación entre 4.1 y 5.0)

#### Diccionario de datos

| Variable                  | Tipo                     | Descripción |
|---------------------------|--------------------------|-------------|
| Items MSLQ                | numérico entero          | Items cuestionario MSLQ |
| lab_1                     | numérico decimal         | Calificación del laboratorio 1 |
| final                     | numérico entero          | Calificación final (0- Bajo desempeño; 1- Medio desempeño; 2- Alto desempeño) |

#### Se importan las librerias

In [1]:
# Librería para matemáticas y estadísticas
### INSERTE SU CÓDIGO AQUÍ 
# Librería para el manejo de datos
### INSERTE SU CÓDIGO AQUÍ 
# Libreria para gráficas
### INSERTE SU CÓDIGO AQUÍ 

# Se importa la libreria para dividir los datos de entrenamiento y de pruebas
### INSERTE SU CÓDIGO AQUÍ 

# libreria para árboles de decisión (clasificación)
### INSERTE SU CÓDIGO AQUÍ 
# Librerias para métricas del modelo de clasificación
### INSERTE SU CÓDIGO AQUÍ 

# Libreria para Árbol de Decisión (Regresión)
### INSERTE SU CÓDIGO AQUÍ 
# Libreria para las métricas
### INSERTE SU CÓDIGO AQUÍ

### Se cargan los datos al dataframe

In [1]:
# Se cargan los registros en un DataFrame 
# y se le asigna el nombre a las columnas
data = pd.read_csv("data/data_mslq.csv", sep=";")

data

,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,...,I13,I14,I15,I16,I17,I18,I19,I20,lab_1,final
0,4,7,3,7,2,4,3,7,3,5,...,4,5,1,5,3,3,3,1,3.8,0
1,1,7,7,5,5,2,7,7,5,1,...,1,1,2,3,1,1,2,1,4.1,2
2,5,7,2,7,7,7,7,7,1,7,...,3,7,2,7,1,1,3,7,4.0,2
3,1,4,6,6,4,5,6,2,5,1,...,6,1,1,3,1,5,5,6,3.5,2
4,5,7,6,6,7,6,6,6,7,7,...,5,6,6,6,5,4,7,7,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,4,6,5,5,5,5,5,5,4,4,...,5,4,4,6,3,4,5,5,5.0,2
203,1,7,7,7,7,7,7,7,7,7,...,5,3,3,7,3,3,7,1,4.7,0
204,1,4,7,4,7,5,7,4,6,1,...,1,3,1,5,1,1,5,6,5.0,2
205,7,7,7,7,7,7,3,4,7,7,...,7,4,1,7,2,7,7,7,5.0,0
206,5,7,6,7,7,7,7,6,7,6,...,5,6,5,7,6,7,6,7,5.0,2

### Preprocesamiento de datos

In [3]:
# Se buscan registros NaN para eliminarlos

###
### INSERTE SU CÓDIGO AQUÍ 
###

Columna  Cantidad NaN
I1       0
I2       0
I3       0
I4       0
I5       0
I6       0
I7       0
I8       0
I9       0
I10      0
I11      0
I12      0
I13      0
I14      0
I15      0
I16      0
I17      0
I18      0
I19      0
I20      0
lab_1    0
final    0
dtype: int64
(207, 22)

In [4]:
# Se consulta la cantidad de registros para Grade2

###
### INSERTE SU CÓDIGO AQUÍ 
###

final
0    55
1    73
2    79
dtype: int64

In [5]:
# Se realiza el resample
from sklearn.utils import resample

###
### INSERTE SU CÓDIGO AQUÍ 
###

0    79
1    79
2    79
Name: final, dtype: int64

In [2]:
# Se genera las estadísticas del DataFrame
data2.describe()

,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,...,I13,I14,I15,I16,I17,I18,I19,I20,lab_1,final
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,...,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000
mean,3.628019,5.908213,5.077295,5.884058,5.391304,5.623188,5.260870,4.864734,4.748792,3.855072,...,3.565217,4.246377,4.376812,5.826087,3.536232,3.323671,5.198068,4.342995,3.596135,1.115942
std,1.978473,1.155939,1.769158,1.271833,1.453660,1.255297,1.389826,1.643186,1.785781,1.972692,...,1.906643,1.754930,1.681725,1.165314,1.899768,1.969813,1.363318,1.543303,1.554881,0.798109
min,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,2.000000,5.000000,4.000000,5.000000,5.000000,5.000000,4.000000,4.000000,3.000000,2.000000,...,2.000000,3.000000,3.000000,5.000000,2.000000,1.500000,4.000000,3.000000,3.200000,0.000000
50%,4.000000,6.000000,5.000000,6.000000,5.000000,6.000000,5.000000,5.000000,5.000000,4.000000,...,4.000000,4.000000,5.000000,6.000000,4.000000,3.000000,5.000000,4.000000,4.100000,1.000000
75%,5.000000,7.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,6.000000,5.000000,...,5.000000,6.000000,6.000000,7.000000,5.000000,5.000000,6.000000,5.000000,5.000000,2.000000
max,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,5.000000,2.000000

In [4]:
# Se observa el tipo de datos de las columnas
data2.dtypes

I1         int64
I2         int64
I3         int64
I4         int64
I5         int64
I6         int64
I7         int64
I8         int64
I9         int64
I10        int64
I11        int64
I12        int64
I13        int64
I14        int64
I15        int64
I16        int64
I17        int64
I18        int64
I19        int64
I20        int64
lab_1    float64
final      int64
dtype: object

### ----------------------------------------

### PUNTO 1: Predicción con Árbol de Decisión - Clasificación (todas las características)

#### Se crea el set de entrenamiento y de pruebas

In [8]:
# Se definen los valores de las características	
features = ['I1','I2','I3','I4','I5','I6','I7','I8','I9','lab_1']
			
# calificación

###
### INSERTE SU CÓDIGO AQUÍ 
###

# Métricas

###
### INSERTE SU CÓDIGO AQUÍ 
###

Precisión: 0.72
Precisión: 0.71
Precisión: 0.69

### PREDICCIÓN ###

In [9]:
# Se genera la predicción con DT
y = pd.DataFrame({'I1':    [4], 
                  'I2':    [6],
                  'I3':    [4],
                  'I4':    [7],
                  'I5':    [5],
                  'I6':    [6],
                  'I7':    [6],
                  'I8':    [7],
                  'I9':    [7],
                  'lab_1': [4.6]})

x = dtc.predict(y)

if x == 0:
    print(x, "- Desempeño Bajo (calificación entre 0.0 y 2.9)")
elif x == 1:
    print(x, "- Desempeño Medio (calificación entre 3.0 y 4.0)")
else:
    print(x, "- Desempeño Alto (calificación mayor a 4.0) ")

[2] - Desempeño Alto (calificación mayor a 4.0)

### ----------------------------------------

### PUNTO 2: Predicción con Árbol de Decisión - Regresión (todas las características)

In [10]:
# Se seleccionan las características 	
features = ['I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12','I13','I14','I15','I16','I17','I18','I19','I20']                   
X = data2[features]
# Variable Objetivo
y = data2['lab_1']

###
### INSERTE SU CÓDIGO AQUÍ 
###

R2: 0.26
RMSE: 1.5
MAE: 0.8

### PREDICCIÓN

In [11]:
# Se genera la predicción con DT
y = pd.DataFrame({'I1':  [4], 
                  'I2':  [6],
                  'I3':  [4],
                  'I4':  [7],
                  'I5':  [5],
                  'I6':  [6],
                  'I7':  [6],
                  'I8':  [7],
                  'I9':  [7],
                  'I10': [5],
                  'I11': [6],
                  'I12': [6],
                  'I13': [7],
                  'I14': [4],
                  'I15': [5],
                  'I16': [5],
                  'I17': [6],
                  'I18': [6],
                  'I19': [7],
                  'I20': [4]})

x = dtr.predict(y)

print("Lab 1:", x)

Lab 1: [2.8]